apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: martian-services
  annotations:
    github.com/project-slug: mmaheu/martian-services
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: martian-relations-team
  system: martian-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
